name: Generate documentation
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.x
          run_install: true

      - name: Get docs
        run: pnpm run docs

      - name: Upload to GH Pages
        run: npx gh-pages -d docs
